### ISSUE TITLE
Error in staging

### ISSUE THREAD

**Issue by NerdDiffer** [Zesty-Stocking/ReelTime#28]
Visit [staging](https://staging-reeltime.herokuapp.com/).

Error message in client console reads:

`WebSocket connection to 'wss://https//staging-reeltime.herokuapp.com:3000/peerjs/peerjs?key=peerjs&id=xxx&token=xxx' failed: Error in connection establishment: net::ERR_NAME_NOT_RESOLVED`
#### Similar situations:
- [SO](http://stackoverflow.com/questions/35035998/websocket-error-in-connection-establishment-neterr-connection-closed)

Could be problem regarding the `https` protocol in staging? Official [README](https://github.com/peers/peerjs-server#run-peerserver) says to reference the SSL certificate if using HTTPS.

**Comment by daredia** [comment]
@NerdDiffer is your url malformed? the error message seems to be missing a colon after https, and also see Request Url in the below image

![image](https://cloud.githubusercontent.com/assets/3240781/17268494/abfac6a2-55df-11e6-8e9e-8b9a0e061ee2.png)
